#!/bin/bash

   sudo su
   yum -y install cacti
   yum -y install mariadb-server
   yum -y install php-process php-gd php
   systemctl enable mariadb
   systemctl enable httpd
   systemctl enable snmpd
   systemctl start mariadb
   systemctl start httpd
   systemctl start snmpd
   mysqladmin -u root password
   mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -p mysql
   echo "create database cacti;
   GRANT ALL ON cacti.* TO cacti@localhost IDENTIFIED BY 'cactipass';  # Set this to somthing better than 'cactipass'
   FLUSH privileges;
   GRANT SELECT ON mysql.time_zone_name TO cacti@localhost;            # Added to fix a timezone issue
   flush privileges;" > stuff.sql
   cat stuff.sql 
   mysql -u root  -p < stuff.sql
   rpm -ql cacti|grep cacti.sql
   mysql cacti < /usr/share/doc/cacti-1.1.37/cacti.sql -u cacti -p
   mysql cacti < /usr/share/doc/cacti-1.1.37/cacti.sql -u cacti -p
   vim /etc/cacti/db.php 
   /etc/httpd/conf.d/cacti.conf
   vim /etc/httpd/conf.d/cacti.conf
   systemctl restart httpd.service
   sed -i 's/#//g' /etc/cron.d/cacti
   vim /etc/php.ini
   vim /etc/php.ini
   setforce 0
