#!/bin/bash
#Install a nagios server

yum -y install nagios

systemctl enable nagios
systemctl start nagios

yum install -y httpd nagios-selinux

systemctl enable httpd
systemctl restart httpd

yum -y install nrpe

systemctl enable nrpe
systemctl start nrpe
